image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - formatcheck
  - build
  - test

variables:
  NUGET_PACKAGES: "/.nuget/packages"

before_script:
  - apt-get update -yq
  - apt-get install -y nuget
  - apt-get install -y dotnet-sdk-8.0
  - nuget restore
  - dotnet tool install fantomas --version 6.0
  - dotnet tool install fake-cli dotnet-fsharplint paket
  - dotnet paket install

formatcheck:
  stage: formatcheck
  script:
    - dotnet fantomas --check problem12 Tests

build:
  stage: build
  script:
    - dotnet fake build

test:
  stage: test
  script: 
    - dotnet test
